#!/usr/local/bin/bash

trap true HUP

if [ "$1" == "confirmed" ]; then
    {
        cp /conf/config.xml /tmp/config.xml.bak

        let timetosleep="$2*60"
        sleep $timetosleep
        
        if [ $? == 0 ]; then
            #we didn't get killed
            cp /tmp/config.xml.bak /conf/config.xml
            reboot
        fi
    } & disown #run in background
fi

if [ "$1" == "confirm" ]; then
    kill $(ps aux | grep '[c]onfirmed' | awk '{print $2}' | tr -d '\n') 2>/dev/null
    rm /tmp/config.xml.bak
fi


